name: 01-building-blocks
on:
    push:
        branches: "main"
jobs: 
    echo-hello:
            runs-on: ubuntu-latest
            steps:
                - name: FirstJob
                  run: echo "hello world"
    echo-goodbye:
            runs-on: ubuntu-latest
            steps:
                - name: Say hello
                  run: echo "I will fail"