name: Event Filter and Activity
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR is opened or synchronized and base branch is main"
